unit Unit1;
 
// if you are using DELPHI, {$DEFINE DELPHI}
// Generated by DFMToPas 
// this source should compile under Delphi and FPC+LCL
 
{$IFNDEF DELPHI}
 {$mode delphi}
{$ENDIF}
 
 interface
 
 uses Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
      StdCtrls, ExtCtrls, Buttons, Menus;
 
 type
 TForm1
 = class(TForm)
   private
   { Private declarations } 
   {$I Unit1def.pas}
   public
   { Public declarations } 
     constructor Create(AOwner: TComponent); override;
     destructor Destroy;  override;
   end;
 
 var Form1:TForm1
;
 
 implementation
 
 {$IFDEF DELPHI}
   {$R *.DFM}
 {$ENDIF}
 
 constructor TForm1
.Create(AOwner: TComponent);
 begin
 inherited Create(AOwner);
 {$I Unit1rc.pas}
 end;
 
 destructor TForm1
.Destroy;
 begin
 inherited Destroy;
 end;
 
 end.
